version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bikeshop_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - DATABASE_URL=sqlite:///database/marcusshop.db
    entrypoint: ["python"]
    command: ["run.py"]

  frontend:
    build: ./frontend
    container_name: bikeshop_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=5173
    command: ["npm", "run", "dev", "--", "--host"]